# Site settings
author: Todd Stoneberg
title: New Beginnings
header-img: img/home-bg.png
email: todd.stoneberg@gmail.com
copyright_name: Todd Stoneberg
description: > # this means to ignore newlines until "baseurl:"
  Begin to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  codeski

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
